# Generated by Django 4.1.6 on 2023-02-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_rename_genre_trope_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingosheet',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gui.genre'),
            preserve_default=False,
        ),
    ]
