# Generated by Django 4.1.6 on 2023-02-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_bingosheet_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingosheet',
            name='bingo_done',
            field=models.BooleanField(default=False),
        ),
    ]
