# Generated by Django 4.1.6 on 2023-02-12 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'friend request', 'verbose_name_plural': 'friend requests'},
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
