# Generated by Django 4.1.6 on 2023-02-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_type_alter_friendrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingosheet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.type'),
        ),
        migrations.AddField(
            model_name='personaltrope',
            name='types',
            field=models.ManyToManyField(default=None, related_name='personal_trope_types', to='gui.type'),
        ),
        migrations.AddField(
            model_name='trope',
            name='types',
            field=models.ManyToManyField(default=None, related_name='trope_types', to='gui.type'),
        ),
    ]
